// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmY33_C39mTjretin7qUZqrc56cEsDGL4',
    appId: '1:980153311724:web:f0769df8f4ff2cf13560c9',
    messagingSenderId: '980153311724',
    projectId: 'expensetracker-b6e55',
    authDomain: 'expensetracker-b6e55.firebaseapp.com',
    storageBucket: 'expensetracker-b6e55.firebasestorage.app',
    measurementId: 'G-DRXZVY4D5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhhifaPqr9HSBiG30YswtJsJjqCH42cs8',
    appId: '1:980153311724:android:c7f7bbc8c33668753560c9',
    messagingSenderId: '980153311724',
    projectId: 'expensetracker-b6e55',
    storageBucket: 'expensetracker-b6e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkAoSisDneUpvzEiyqYrsUpebZCe_stns',
    appId: '1:980153311724:ios:c9d45a649c671de93560c9',
    messagingSenderId: '980153311724',
    projectId: 'expensetracker-b6e55',
    storageBucket: 'expensetracker-b6e55.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkAoSisDneUpvzEiyqYrsUpebZCe_stns',
    appId: '1:980153311724:ios:c9d45a649c671de93560c9',
    messagingSenderId: '980153311724',
    projectId: 'expensetracker-b6e55',
    storageBucket: 'expensetracker-b6e55.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmY33_C39mTjretin7qUZqrc56cEsDGL4',
    appId: '1:980153311724:web:e147ca5842bf109c3560c9',
    messagingSenderId: '980153311724',
    projectId: 'expensetracker-b6e55',
    authDomain: 'expensetracker-b6e55.firebaseapp.com',
    storageBucket: 'expensetracker-b6e55.firebasestorage.app',
    measurementId: 'G-MGSXNJYG6K',
  );

}